### ISSUE TITLE
Lollipop update view problem

### ISSUE THREAD

**Issue by abhishek-ramkrishna** [jraska/Falcon#27] opened 2018-01-09 09:16 UTC
The falcon library works great across android versions. But i see a concern with lollipop. When the view gets updated, eg: Tap on edit text and start typing. Now use falcon to capture screen . The screen shot has old view where it was not  updated. However it works well on jelly bean,kit kat, marshmallow,nougat & Oreo.

Thanks.

**Comment by jraska** [comment] 2018-01-10 17:50
Hello, 

Could you please provide some test case demonstarting the issue?

The problem is the only thing Falcon does at the end is calling `View.draw(Canvas)` on the root view. 

The problem you are describing sounds like the View is not drawing it to the Canvas and I'm afraid Falcon can do very little about it.

**Comment by jraska** [comment] 2018-01-23 19:58
@abhishek-ramkrishna Any update here please?

**Comment by jraska** [comment] 2018-02-06 21:21
Closing this now for lack of information. Please if you can attach stack trace or better test case reproducing this that would help. Please reopen the issue in such case.

**Closed by jraska** 2018-02-06 21:21 UTC
