### ISSUE TITLE
Progress dialog Issue

### ISSUE THREAD

**Issue by Sorbh** [jraska/Falcon#20] opened 2016-12-14 14:15 UTC
Hello,
My application is capturing screen shot  in every 500ms using your library to gether user behavior imformation, everything working fine until progress dialog shown by app, after it appear in every frame even though its been dismissed in application but its still showing in frame or screenshot. Only facing this problem with progress dialog , alert dialog or other custom dialog box working fine.
Please check the attached GIF
 **Processing image** progress dialog stick to frames.

![out](https://cloud.githubusercontent.com/assets/8159377/21185216/c2fc395e-c235-11e6-9ee9-702acb50a770.gif)

**Comment by jraska** [comment] 2016-12-14 20:40
Hello, thanks for reporting this with such good image. :)

Please could you provide sample which will reproduce that? I'm afraid it will be difficult for me to reproduce and fix it without that.

Maybe just an idea is progress dialog properly dismissed? As I see on gif it is overlayed with AlertDialog and then new activity is started or previous one with ProgressDialog finished?

Thanks

**Comment by jraska** [comment] 2017-02-02 19:48
I tried to reproduce the issue with progress dialog and I cannot make it. If this is still happening to you please reopen the issue and maybe provide brief sample of the behaviour.

Closing it now as I cannot reproduce it.

**Closed by jraska** 2017-02-02 19:48 UTC
Labels: bug
