### ISSUE TITLE
Fails to capture screenshot with hardware bitmaps

### ISSUE THREAD

**Issue by build3r** [jraska/Falcon#51] opened 2020-11-17 08:25 UTC
The app crashes because the device does not support hardware bitmaps.
Device: Xiaomi Redmi 6 Pro
Os: 8.1.0, MIUI Global 10.0
Logs:
```
    java.lang.IllegalStateException: Software rendering doesn't support hardware bitmaps
        at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:532)
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:120)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1434)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
        at coil.drawable.CrossfadeDrawable.draw(CrossfadeDrawable.kt:69)
        at android.widget.ImageView.onDraw(ImageView.java:1367)
        at android.view.View.draw(View.java:19226)
        at android.view.View.draw(View.java:19096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at android.view.View.draw(View.java:19096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
        at android.view.View.draw(View.java:19096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:1998)
        at android.view.View.draw(View.java:19096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:19229)
        at android.view.View.draw(View.java:19096)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:235)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:223)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1882)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19094)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
2020-11-17 13:33:17.681 28782-28782/**** E/Falcon:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at com.android.internal.policy.DecorView.draw(DecorView.java:791)
        at com.jraska.falcon.Falcon.drawRootToBitmap(Falcon.java:177)
        at com.jraska.falcon.Falcon.drawRootsToBitmap(Falcon.java:162)
        at com.jraska.falcon.Falcon.takeBitmapUnchecked(Falcon.java:127)
        at com.jraska.falcon.Falcon.takeScreenshotBitmap(Falcon.java:90)
        at com.linkedin.android.shaky.Shaky.getScreenshotBitmap(Shaky.java:226)
        at com.linkedin.android.shaky.Shaky.doStartFeedbackFlow(Shaky.java:143)
        at com.linkedin.android.shaky.Shaky.access$100(Shaky.java:49)
        at com.linkedin.android.shaky.Shaky$1.onReceive(Shaky.java:259)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)```

**Comment by jraska** [comment] 2020-11-18 16:31
Hey, thanks for the issue.

I don't think Falcon is a cause of this. All what Falcon does is drawing the layout into bitmap. This is done by calling draw(Canvas) method.

The error seems to be caused somewhere within the view drawing. Falcon itself doesn't use any hardware support.

The error disappears when removing Falcon? 
If so then I would need a standalone example to reproduce, but I'm afraid I cannot help here much.

**Comment by jraska** [comment] 2020-11-18 16:34
`coil.drawable.CrossfadeDrawable` this line seems to be the one using the HW drawing. As the error says we seem not to be able to capture such bitmap into canvas.

**Comment by build3r** [comment] 2020-11-19 08:46
@jraska You are right that the hardwarebitmaps were drawn by coil Imageloading library.
The app/library crashes when there are images loaded with coil Image loading library. 

By disabling hardwarebitmaps the screenshot functionality works.
Apparently hardware bitmaps is a major optimization for drawing on canvas.
Quote by @colinrtwhite (Coil  image loading library contributor)
>  Hardware bitmaps are a pretty big optimization so I'd want to avoid disabling them. For the crashes, can you let me know if the devices you saw crashes for are in this list? There are a number of devices with hardware-specific issues that I'm working on blocking.

May be Falcon can add support taking screenshots where images are drawn with hardwarebitmaps.

**Comment by colinrtwhite** [comment] 2020-11-19 19:28
@jraska I believe the [`PixelCopy`](https://developer.android.com/reference/android/view/PixelCopy) APIs are needed to grab a screenshot of a view using hardware bitmaps.

@build3r You can disable hardware bitmaps using `ImageLoader.allowHardware(false)` to work around this issue - though this will use software bitmaps on API 26+ which are slower and consume more memory.

**Comment by build3r** [comment] 2020-11-20 09:11
@colinrtwhite Already did disable hardware bitmaps as a quick fix. 
@jraska But I believe screenshot tool should be agnostic of how the bitmaps were drawn. May we add the support using PixelCopy as mentioned above. Please let me know if I can help in anyway.

**Comment by jraska** [comment] 2020-11-22 13:38
Hey, although I agree this shouldn't be a problem for screenshots, by some investigation it seems lke a large task.

### For Context
It is important to explain that Falcon works on the level of Windows and root views and puts the different windows(Dialogs, Activity Window) into one bitmap in proper order and with correct offsets.

https://github.com/jraska/Falcon/blob/bf8100136eee32cc64e7e93746eb7fd9aa2c9cdf/falcon/src/main/java/com/jraska/falcon/Falcon.java#L201

The traversal of View trees and individual views is left to the Android framework, otherwise the complexity of different view types will simply explode the complexity. This is also why for example [Google Maps](https://github.com/jraska/Falcon/issues/24) or [Lottie](https://github.com/jraska/Falcon/issues/46) are not supported.
https://github.com/jraska/Falcon/blob/bf8100136eee32cc64e7e93746eb7fd9aa2c9cdf/falcon/src/main/java/com/jraska/falcon/Falcon.java#L177

This is to explain why I wouldn't go the path of being View type agnostic.

### The `PixelCopy` option

Looking at the [PixelCopy API](https://developer.android.com/reference/android/view/PixelCopy), we need a `Surface` or `Window` - reading more [the docs of `PixelCopy.request(Window, ...)`](https://developer.android.com/reference/android/view/PixelCopy?hl=en#request(android.view.Window,%20android.graphics.Bitmap,%20android.view.PixelCopy.OnPixelCopyFinishedListener,%20android.os.Handler)) I See
> The most recently queued buffer in the Window's Surface will be used as the source of the copy. Note: This is limited to being able to copy from Window's with a non-null DecorView. 

So there is potentially a way. The problem is we need somehow get the reference to all `Window` objects of all `ViewRootImpl` for `PixelCopy`

<img width="492" alt="Screenshot 2020-11-22 at 14 19 47" src="https://user-images.githubusercontent.com/6277721/99904896-26286a00-2cce-11eb-83ee-4bd8f13ff064.png">
<img width="384" alt="Screenshot 2020-11-22 at 14 19 54" src="https://user-images.githubusercontent.com/6277721/99904907-29bbf100-2cce-11eb-96db-66f9dc2b7975.png">


I did a quick trial using `PixelCopy` with changes above, the problem is it brings a whole new domain of problems that the offsets don't match with multiple windows screenshots, the popup windows and dialogs don't have a `DecorView` etc. Basically all the problems `Falcon` solves now would have to be solved a different way, which makes it a rewrite of the whole thing :D

### In case you want to help
- Please copy paste `Falcon.java` (it's one file) and try the changes with PixelCopy to see if it will solve the hardware problem.
- If it does - try the `falcon-sample` from this repo with the change to understand what I mean by new domain of problems :).
- This will give us an estimate how many other problems we would have to solve.
![Screenshot_20200908-115932](https://user-images.githubusercontent.com/6277721/99905161-60463b80-2ccf-11eb-8eb9-25bf38b36a0e.png)
### My conclusion so far
My impression now is we would have to rewrite everything
- Offsetting of different windows
- Awaiting for the callbacks
- Composing multiple windows together for cases of dialogs, toasts...

So the `PixelCopy` seems definitely a better option, but it also seems pretty expensive in time for rewrite, so I'm not sure if it is worth it.
At some point I want to move the whole thing to Kotlin so that could be a good opportunity, but now I think I will not do it unless there is some help above, simply because it will take several days with unsure output and also risks of breaking many edge cases.

I hope it makes sense, let me know what you think and if the `PixelCopy` copy/paste solution worked for you :)

**Comment by jraska** [comment] 2021-01-17 12:14
Hey @build3r , pleas did you get a chance to try the PixelCopy for your case? :) Thanks

**Comment by build3r** [comment] 2021-01-18 08:02
@jraska I did try a workaround using `bitmap.copy(Bitmap.Config.RGBA_F16, true)` which I thought would change the the way bitmaps are drawn dynamically but that was a **dead end**. For my use case i was using coil only on two screens so it was quicker to just disable hardware bitmaps on those screens.

**Comment by build3r** [comment] 2021-01-18 08:09
However I did find this project which successfully uses PixelCopy Api for taking screenshots
https://github.com/bolteu/screenshotty
Implementation: 
https://github.com/bolteu/screenshotty/blob/master/screenshotty-lib/src/main/java/eu/bolt/screenshotty/internal/pixelcopy/PixelCopyDelegateV26.kt
Though this falls back on MediaProjection api when the above fails, which might be too much for many use cases.

**Comment by jraska** [comment] 2021-01-18 19:26
Thanks a lot @build3r for answer and for these references. :)

As far as I understand you are not blocked anymore? 
If not, I will close this issue and possibly follow up with a PixelCopy implementation, however I'm not sure when I will have time for i. It seems like a large task to rewrite it and maintain properly along the current implementation.

**Comment by build3r** [comment] 2021-01-19 09:48
@jraska Thanks for the consideration, I too understand its a big effort to port over to Pixel copy. But in the mean time we can handle the crash due to hardware drawables and also mention it in readme. Its better to skip an hardware accelerated image than to crash the library/app.
Let me know if you think the above suggestion make sense will send a PR with the fix,

**Comment by jraska** [comment] 2021-01-30 15:25
Hey, so it depends what would be the failover scenario? 

If it would be be silently no screenshot then I would argue crash is actually better, because this would bring the engineers here and complain, which is what I prefer instead of silently not taking the screenshot. If we keep the crash we would know better who actually have the same problem. 

Or which type of handling do you have in mind?

**Comment by jraska** [comment] 2021-02-25 20:53
Please reopen the issue if some new info will come :) Now I'm closing it as inactive.

**Closed by jraska** 2021-02-25 20:53 UTC
