### ISSUE TITLE
Usage of Undocumented API (API 29)

### ISSUE THREAD

**Issue by TimoPtr** [jraska/Falcon#38] opened 2018-08-21 08:02 UTC
Your tool use reflection on some Field which are block by the SDK on API 28. When the target is 28 you get an Exception : 
`
com.jraska.falcon.Falcon$UnableToTakeScreenshotException: java.lang.NoSuchFieldException: Field mWindowTop not found for class class android.view.View$AttachInfo`

See the documentation here :
https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

And a working fix is to set system property from adb to disable this restriction :

`  adb shell settings put global hidden_api_policy_pre_p_apps  1
  adb shell settings put global hidden_api_policy_p_apps 1
`

A solution would be to ask to Google to allow access to the fields mWindowTop, mWindowLeft

**Comment by jraska** [comment] 2018-08-21 10:54
Hello, thanks for reporting this. 

I will try to find some workaround for this. Apparently other reflection seems to work since Falcon takes other fields in flow before accessing this one so lets see if we could use some thing else or better APIs are present in API 28 so less or none reflection is needed.

**Comment by jraska** [comment] 2018-08-22 16:29
Please have a look at version 2.1.0

`androidTestCompile 'com.jraska:falcon:2.1.0'`

It should work now on Android 9.

Please let me know if it helped :)

**Comment by TimoPtr** [comment] 2018-08-24 14:30
It works very well. Thanks you ;)

**Comment by ChanSek** [comment] 2019-07-04 11:52
I am facing this crash in 2.1.1 too. And it started occurring after I migrated my project to androidx.

**Comment by jraska** [comment] 2019-07-14 16:40
Hello @ChanSek , 

Can you please send me a stack trace you are getting with a note about using undocumented API? 

Thank you.

**Comment by 1hakr** [comment] 2019-08-01 11:57
@jraska i'm getting this error. It works fine for target Sdk Version 28 but with 29 it crashes.

`    Caused by: java.lang.NoSuchFieldException: Field mWindowTop not found for class class android.view.View$AttachInfo
        at com.jraska.falcon.Falcon.findField(Falcon.java:347)
        at com.jraska.falcon.Falcon.getFieldValueUnchecked(Falcon.java:329)
        at com.jraska.falcon.Falcon.getFieldValue(Falcon.java:321)
        at com.jraska.falcon.Falcon.viewRootData(Falcon.java:239)
        at com.jraska.falcon.Falcon.getRootViews(Falcon.java:210)
        at com.jraska.falcon.Falcon.takeBitmapUnchecked(Falcon.java:103)
        at com.jraska.falcon.Falcon.takeScreenshotBitmap(Falcon.java:88)`

**Comment by jraska** [comment] 2019-08-02 16:34
Thanks a lot for the stack trace.

Some new methods were blacklisted. I will have to look into it and figure out if we can avoid using reflection for these fields triggering errors.

**Comment by jraska** [comment] 2019-08-05 17:52
@1hakr Can you please check which version of Falcon you are using? In the stack trace I see the field `mWindowTop`, which was removed from the reflection part as part of the update: https://github.com/jraska/Falcon/pull/39.

Please check again with Falcon version `2.1.1`. Thanks

**Comment by 1hakr** [comment] 2019-08-05 17:56
@jraska , i checked and i'm not getting the crash anymore, strange!

**Comment by jraska** [comment] 2019-09-10 17:33
I checked again version `2.1.1` with API 29 and seems to work ok for me. Closing now

**Closed by jraska** 2019-09-10 17:33 UTC
Labels: bug
